name: cpp-linter

on:
  push:
    branches: [ 299-setup-code-formatter ]
  pull_request:
    branches: [ main, dev ]

jobs:
  cpp-linter:
    permissions:
      pull-requests: write
      contents: write
      actions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        continue-on-error: true
        with:
          style: 'llvm'
          files-changed-only: false
          file-annotations: true
          thread-comments: true
