name: cpp-linter

on:
  push:
    branches: [ main, dev, 299-setup-code-formatter ]
  pull_request:
    branches: [ main, dev ]

jobs:
  cpp-linter:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@main
        id: linter
        continue-on-error: true
        with:
          style: './.clang-format'
          files-changed-only: false
          thread-comments: true
          format-review: true
